### ISSUE TITLE
Write cryptographic flow for authenticating a user

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt-spec#10]
This should capture the expected communications between a local client and the key servers.

**Comment by indomitableSwan** [comment]
See also #11. We may want to call `retrieve_storage_key` by default as part of the flow for authenticating a user.

**Comment by indomitableSwan** [comment]
Upon completion, @indomitableSwan or @marsella should write corresponding ticket(s) in key-mgmt.
