### ISSUE TITLE
Separate internal `user_id` from user account information used in OPAQUE.

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/key-mgmt-spec#102]
In the current implementation, we conflated the user account information used in OPAQUE (normally, e.g., a user email or other memorable account information) with an internal, universally unique identifier for the user (`user_id`).

We fixed this conflation problem in the specification; for more details see:
- the new version of _registration sessions_ [here](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/systems-architecture.md#opening-and-using-a-registration-session) 
- a diff of relevant changes [here](https://github.com/boltlabs-inc/key-mgmt-spec/pull/99).

This epic will be complete when the implementation reflects these changes, which includes:
- [x] refactoring registration
- [x] refactoring authentication
- [ ] confirming that any impacted WIP has been updated appropriately.

**Comment by marsella** [comment]
Some preliminary work is on the [131-register-cryptography](https://github.com/boltlabs-inc/key-mgmt/tree/131-register-cryptography) branch, which makes the two different types but doesn't start to define where they are each used and created.

**Comment by marsella** [comment]
I am not confident about separating this work into multiple issues. I think it might have to be one big PR. I will make a child issue for now but I'm afraid it will encompass everything.

**Comment by indomitableSwan** [comment]
> I am not confident about separating this work into multiple issues. I think it might have to be one big PR. I will make sub-issues for now but I'm afraid they will end up all being done in one.

I wouldn't work too hard on making separate issues in that case.
