### ISSUE TITLE
Write cryptographic flow for registering a user

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt-spec#11]
This should capture the expected communications between a local client and the key servers and detail the OPAQUE suite used.

**Comment by indomitableSwan** [comment]
The client-side output of the registration flow MUST include:
- `user_id`, A (globally unique) user identifier
- `session_key` A shared secret the client shares with the key server.

The server-side output of registration MUST include:
- `user_id`, A (globally unique) user identifier that matches that of the client.
- `session_key`, A shared secret that matches that of the key server.

A rough sketch of the registration flow details:
- An OPAQUE registration by the client. Client outputs here will include `export_key`, which will be used locally by the client during the lifetime of the session, but never stored.
- The generation of a symmetric encryption key `storage_key`. This key will be used by the client to encrypt arbitrary secrets for both local and remote storage. This key should also be used locally by the client during the lifetime of the session, but never stored.
- The local client should encrypt `storage_key` under (a key derived from, with domain separation) `export_key` and store the resulting ciphertext at the key server.

The client will also need a corresponding`retrieve_storage_key` function.

**Comment by indomitableSwan** [comment]
Upon completion, @indomitableSwan or @marsella should write corresponding ticket(s) in key-mgmt.
