### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by indomitableSwan** [boltlabs-inc/key-mgmt-spec#3]
The README should capture:

- [x] The goals of the repository: At a high level, we want to capture information that helps developers and the public understand what the key-mgmt project accomplishes and what underlying cryptographic protocols are used. What is out of scope: capturing granular implementation and software architecture decisions that should be documented clearly in [key-mgmt](https://github.com/boltlabs-inc/key-mgmt). 
- [x] A concrete description of what should be included in this repo.

Here is a working list of what should be included in this repo:
- An overview of what the product is expected to accomplish in our current development phase. Because we are designing and implementing the product iteratively, this should be updated regularly.
- Integration guidance for developers, including any requirements or assumptions for the calling application(s) and how the calling application(s) fits in the overall system architecture, i.e., which components are external-facing. This will be helpful for iterating on our external-facing APIs and overall system functionality.
- A specification of the system's application-layer session handling. This will be helpful for design iteration, analysis, audits, and obtaining feedback from the community.
- A specification of the system's cryptographic protocol flows. This will be helpful for design iteration, analysis, audits, and obtaining feedback from the community.

Question: What's missing?

**Comment by marsella** [comment]
How do you imagine this resource will be used by developers who want to use the library? Is this a supplementary resource or a primary piece of documentation for them to read? 

If the latter, we could also consider wrapping it into the rustdoc in the main repo as an additional page, like [the `notes` module in the BLS12-381 library](https://docs.rs/bls12_381/latest/bls12_381/).

Clarifying question:
- "application-layer session handling" - I'm not sure what this means. Does this describe the way that the calling application interacts with our library and how to authenticate and create a secure channel?

The current description gears the spec toward two primary groups: developers that are trying to integrate the library; and cryptographers who are trying to audit it. I think this list looks good for developers - they can see the current status and goals, how to integrate, and specific details on dealing with sessions and authentication (if I understood the third bullet correctly).

For the cryptographers, we might want an additional goal of describing cryptographic and security properties that our system maintains and the underlying assumptions that support those properties - that will give context for the protocol flows.

**Comment by indomitableSwan** [comment]
> How do you imagine this resource will be used by developers who want to use the library? Is this a supplementary resource or a primary piece of documentation for them to read?
> 
> If the latter, we could also consider wrapping it into the rustdoc in the main repo as an additional page, like [the `notes` module in the BLS12-381 library](https://docs.rs/bls12_381/latest/bls12_381/).

I like the suggestion of wrapping this specification into the rustdoc. If it's supplemental, it's easier to ignore.

> 
> Clarifying question:
> 
> * "application-layer session handling" - I'm not sure what this means. Does this describe the way that the calling application interacts with our library and how to authenticate and create a secure channel?

Perhaps @gijsvl could chime in to help on clarifying terminology here. I am talking about how we handle logical sessions. We want these to be independent of the transport layer. For example, we may want:
- To support a logical session that spans TCP connections across multiple IP addresses.
- To support packaging multiple logical sessions within a single TCP connection.
> 
> The current description gears the spec toward two primary groups: developers that are trying to integrate the library; and cryptographers who are trying to audit it. I think this list looks good for developers - they can see the current status and goals, how to integrate, and specific details on dealing with sessions and authentication (if I understood the third bullet correctly).
> 
> For the cryptographers, we might want an additional goal of describing cryptographic and security properties that our system maintains and the underlying assumptions that support those properties - that will give context for the protocol flows.

Yes, I was imagining including those details in the specification of the cryptographic protocol flows.
