### ISSUE TITLE
Design authentication details

### ISSUE THREAD

**Issue by gijsvl** [boltlabs-inc/key-mgmt-spec#5]
- [ ] Design the use of a PAKE (OPAQUE)
- [ ] Design the use of the extra layer of encryption using the session key from the PAKE
- [ ] Make drawings of this design

**Comment by marsella** [comment]
This has some overlap with #11.

**Comment by indomitableSwan** [comment]
I believe the first task overlaps #21 as well. I recommend we separate the remaining documentation writing and drawing tasks into two issues and then close.

**Comment by indomitableSwan** [comment]
Closing this issue as superseded by #21, #29 and #30.
