### ISSUE TITLE
Differentiate user identifiers

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt-spec#52]
We are using `user_id` for both OPAQUE and our application, but these identifiers should be different. 
- For OPAQUE, the user identifier should be human-memorable account information
- For our application, user id is a 128-bit UUID.

The likely solution here is that the key server should generate and store the application user ID during registration (#11), and pass it back to the client during authentication (#10).

**Comment by indomitableSwan** [comment]
@marsella I think we should go ahead and make our user IDs internally generated, as you outline above.
