### ISSUE TITLE
Write cryptographic flow for storing a secret

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt-spec#8]
This should capture the expected communications between a local client and the key servers. It can abstract over authentication and registration. It should capture the case where a user wishes to store a secret that they have already created.

**Comment by indomitableSwan** [comment]
Separation of this issue from #9 (originally on just "creating" a secret) has caused internal confusion on the concept of "store" vs "import". Rewrote #9 to capture the full use case of "creating and storing a secret" to avoid this problem.
